version: '3'

services:
  postgres:
    image: 'postgres:16.2'
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres # Default
      POSTGRES_HOST_AUTH_METHOD: trust # No PW required
    ports:
      - '5432:5432'
